
  # Publish all joint states -----------------------------------
#  joint_state_controller:
#    type: joint_state_controller/JointStateController
#    publish_rate: 50  

  # Position Controllers ---------------------------------------
#  joint1_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint1
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  joint2_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint2
#    pid: {p: 100.0, i: 0.01, d: 10.0}
    
    
    
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Eixo1_Roda1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Eixo1_Roda2
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  joint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Eixo1_Roda3
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  joint4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: Eixo1_Roda4
    pid: {p: 100.0, i: 0.01, d: 10.0}
